// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDC-2IZHc3NCXp1lQtOauQMyZ-1Wz5RrE',
    appId: '1:287711278777:web:07e4db55dcb6ef0be44d68',
    messagingSenderId: '287711278777',
    projectId: 'flutter-crush-4ece9',
    authDomain: 'flutter-crush-4ece9.firebaseapp.com',
    storageBucket: 'flutter-crush-4ece9.appspot.com',
    measurementId: 'G-0ZT7HMRWNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaczm3NR2Ypak3xf_qd9oXPqEA5Xk2ybc',
    appId: '1:287711278777:android:7e07ce06498c020ee44d68',
    messagingSenderId: '287711278777',
    projectId: 'flutter-crush-4ece9',
    storageBucket: 'flutter-crush-4ece9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb_8fxyUItwAudejzE7PiwY63JIAT4GAE',
    appId: '1:287711278777:ios:d60c09825ef0c39be44d68',
    messagingSenderId: '287711278777',
    projectId: 'flutter-crush-4ece9',
    storageBucket: 'flutter-crush-4ece9.appspot.com',
    iosClientId: '287711278777-g2l2ojeocifh7a6g0fo2jlkc95jv7k4r.apps.googleusercontent.com',
    iosBundleId: 'com.felpower.fluttercrush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb_8fxyUItwAudejzE7PiwY63JIAT4GAE',
    appId: '1:287711278777:ios:17e51c94ee265f01e44d68',
    messagingSenderId: '287711278777',
    projectId: 'flutter-crush-4ece9',
    storageBucket: 'flutter-crush-4ece9.appspot.com',
    iosClientId: '287711278777-tl4a2sk1ccgq2fn8jncteenm775p2q34.apps.googleusercontent.com',
    iosBundleId: 'com.felpower.projektFlutterCrush.RunnerTests',
  );
}
