name: Send Notification Workflow

on:
  schedule:
    - cron: '0 16 * * *'  # Run every day at 6 PM Austrian Standard Time (UTC+1)
    - cron: '0 15 * 3-10 Sun'  # Run every day at 6 PM Austrian Daylight Saving Time (UTC+2)
  workflow_dispatch:  # Manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install firebase_admin

      - name: Set up Firebase credentials
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: |
          mkdir -p credentials
          echo "$FIREBASE_CREDENTIALS" > credentials/credentials.json

      - name: Verify credentials file
        run: cat credentials/credentials.json

      - name: Run script
        run: |
          cd generators
          python notification_cron.py